# Generated by Django 3.1.2 on 2020-10-02 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_router', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='routerdetails',
            unique_together={('loopback', 'hostname')},
        ),
        migrations.AlterModelTable(
            name='routerdetails',
            table='router_details',
        ),
    ]
